
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sgcsm
    # ?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwertyuiop123
